spring.application.name=spring-rest
spring.datasource.url=jdbc:postgresql://localhost:5432/school_db
spring.datasource.username=postgres
spring.datasource.password=clintarthur

# Reduce logging level, Only warn is displayed
logging.level.root=warn

#Turn of Spring Boot Banner
spring.main.banner-mode=off

#Add logging configs to display SQL stsatements
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdcb.bind=trace

#Configure JPA/Hibernate to auto create the table
spring.jpa.hibernate.ddl-auto=update
